name: GitHub Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0

      - name: Setup | Go
        uses: actions/setup-go@v5.0.1
        with:
          go-version: "^1.15.x"

      - name: Setup | Release Notes
        run: |
          go get -u github.com/git-chglog/git-chglog/cmd/git-chglog
          git-chglog -c .github/chglog/release.yml $(git describe --tags) > RELEASE.md

      - name: Setup | Archive Release
        uses: TheDoctor0/zip-release@0.7.6
        with:
          path: "completions/ conf.d/ functions/"
          filename: emc.fish.zip

      - name: Build | Publish
        uses: softprops/action-gh-release@v2
        with:
          files: emc.fish.zip
          body_path: RELEASE.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
